import Anthropic from "@anthropic-ai/sdk";

// Day 6 — AI-grounded drop-off insight prose for Feature 1 (master plan
// §"Days 4-7"). Two surfaces:
//
// Note: server-only enforcement lives in ./cache.ts (the file that
// touches the DB and reads process.env). This file stays import-pure
// so it's testable under `node --test` without the runtime guard.
//
//   1. Course-level "What we're seeing" banner on /drop-off
//   2. Lesson-level zoom prose on /drop-off/lessons/[id]
//
// Both share the same voice rules from the wisdom doc + master plan
// Part 6: thoughtful operator, names lessons specifically, references
// creator wisdom directly when relevant, honest about uncertainty,
// never growth-marketing or panicked language.
//
// We support two modes:
//   - Anthropic (when ANTHROPIC_API_KEY is set): real LLM with the
//     locked system prompt below
//   - Fallback (no key, or call fails): deterministic rule-based prose
//     grounded in the same wisdom thresholds. Honest signal: the body
//     reads sensibly even without an API key wired up, so creators
//     don't see a blank state in beta when keys are still being set.
//
// Either way the model name is recorded with the cached row so we can
// see in the DB which insights were generated by what.

// We pin a specific Sonnet build instead of "-latest" so a model swap
// doesn't silently change the voice creators are paying for.
const ANTHROPIC_MODEL = "claude-sonnet-4-5-20250929";

const FALLBACK_MODEL_NAME = "fallback-rule-v1";

// Voice locked by docs/skool-success-os-master-plan.md Part 6 + the
// wisdom doc Feature 1 copy direction. Edits here change every
// insight site-wide; treat with care.
const SYSTEM_PROMPT = `You are the AI insight writer inside CourseSuccess, a retention tool for Skool community creators. The reader is a community owner who knows their members by name and is busy. They opened this view to figure out where their course is leaking and what to try.

Voice rules (these are non-negotiable):
- Sound like a thoughtful operator wrote the note, not an analyst.
- Reference the lesson by its actual title and position ("Lesson 3 — New page"), not "the third item".
- Lead with what is happening to members, not the percentage. Never open with a stat.
- Cite the operator wisdom this product is built on when relevant. The strongest priors are:
  - "The longer they stay the less they churn" — getting members past day 90 is the win, so early-course leaks matter most.
  - AI Jack went from 30% to 5.2% churn by deleting content. Before adding new lessons, ask if half this one could be cut.
  - Members aren't full-time in your community; they have jobs and families. Overwhelm is the most common drop-off cause, not lack of interest.
- Be honest about what you don't know. You see completion %, not why they stopped. Say so when relevant.
- Never use panic language ("URGENT", "at risk of churn"). Never use growth-marketing language ("12% improvement", "boost engagement").
- 2 to 4 sentences per response. Plain prose. No bullets, no headings, no emojis.
- The first sentence must contain a specific lesson title in **bold** (markdown), so the UI can highlight it.`;

// Minimal, sortable shape so the same input can render fallback prose
// or feed the LLM. Keep fields cheap to compute — the caller already
// has lessonRows in memory and just hands us a slice.
export interface InsightInput {
  courseTitle: string;
  // 1-indexed position of the worst lesson in the course.
  worstPosition: number;
  worstTitle: string;
  worstCompletionPct: number;
  // Position immediately before/after the worst, if present. Used to
  // describe the "drop" magnitude in narrative form.
  previousPosition: number | null;
  previousTitle: string | null;
  previousCompletionPct: number | null;
  nextPosition: number | null;
  nextTitle: string | null;
  nextCompletionPct: number | null;
  courseLessonCount: number;
  memberCount: number;
}

export interface GeneratedInsight {
  body: string;
  model: string;
}

export interface AnthropicConfig {
  apiKey?: string | null;
  model?: string;
}

// Public entrypoint. Always returns a usable string — falls back when
// the LLM call is unavailable so the UI is never blank.
export async function generateCourseDropOffInsight(
  input: InsightInput,
  config: AnthropicConfig = {},
): Promise<GeneratedInsight> {
  const apiKey = config.apiKey ?? process.env.ANTHROPIC_API_KEY ?? null;
  if (!apiKey) {
    return { body: buildFallbackInsight(input), model: FALLBACK_MODEL_NAME };
  }

  try {
    const client = new Anthropic({ apiKey });
    const userPrompt = buildUserPrompt(input);
    const model = config.model ?? ANTHROPIC_MODEL;

    const response = await client.messages.create({
      model,
      max_tokens: 400,
      system: SYSTEM_PROMPT,
      messages: [{ role: "user", content: userPrompt }],
    });

    const text = extractText(response);
    if (!text) {
      return { body: buildFallbackInsight(input), model: FALLBACK_MODEL_NAME };
    }
    return { body: text, model };
  } catch (err) {
    // Never let an LLM outage break the page. Log and fall back.
    // The fallback prose is good enough that the creator can ship
    // without us; the upgrade is voice quality, not correctness.
    // eslint-disable-next-line no-console
    console.warn("[ai/insights] anthropic call failed, using fallback", err);
    return { body: buildFallbackInsight(input), model: FALLBACK_MODEL_NAME };
  }
}

// Deterministic prose used when ANTHROPIC_API_KEY is not set or the
// API call fails. Chooses one of three "shapes" based on the data so
// the voice still feels human across courses.
export function buildFallbackInsight(input: InsightInput): string {
  const {
    worstTitle,
    worstPosition,
    worstCompletionPct,
    previousCompletionPct,
    previousPosition,
    courseLessonCount,
    memberCount,
  } = input;

  const pctRounded = Math.round(worstCompletionPct);
  const earlyCourse =
    courseLessonCount > 0 && worstPosition <= Math.max(1, Math.ceil(courseLessonCount / 3));
  const drop =
    previousCompletionPct !== null
      ? Math.max(0, Math.round(previousCompletionPct - worstCompletionPct))
      : null;

  // Shape 1 — early-course leak. This is the wisdom-doc "day 90"
  // priority case; the prose explicitly invokes it.
  if (earlyCourse && pctRounded < 50) {
    return [
      `Members are stalling at **Lesson ${worstPosition} — ${worstTitle}**, and it's early in the course.`,
      `Only ${pctRounded}% of the ${memberCount} ${plural(
        "member",
        memberCount,
      )} we're tracking get past it. Early drop tends to mean members never come back, so this is the spot worth fixing first.`,
      `Andrew Kirby's rule of thumb: when an early lesson leaks, splitting it or adding a quick win in front of it usually does more than rewriting it from scratch.`,
    ].join(" ");
  }

  // Shape 2 — clear drop from the previous lesson. Highlight the
  // magnitude rather than the absolute %.
  if (drop !== null && drop >= 15) {
    return [
      `**Lesson ${worstPosition} — ${worstTitle}** is where momentum is dying.`,
      `Completion drops about ${drop} points from the lesson before it (${pctRounded}% vs ${Math.round(
        previousCompletionPct ?? 0,
      )}% on Lesson ${previousPosition}).`,
      `That kind of cliff usually points at an effort jump — length, density, or a missing step in between. AI Jack's playbook applies: ask whether half this lesson could be cut before you consider adding more.`,
    ].join(" ");
  }

  // Shape 3 — no dramatic cliff, but a leak at the worst lesson.
  // Honest about uncertainty.
  return [
    `**Lesson ${worstPosition} — ${worstTitle}** has the lowest completion in this course at ${pctRounded}% across ${memberCount} ${plural(
      "member",
      memberCount,
    )}.`,
    `We can see they stop here; we can't see why. The fastest signal is to open the lesson and read it the way a member with 30 minutes a week would read it — most leaks turn out to be effort, not interest.`,
  ].join(" ");
}

function buildUserPrompt(input: InsightInput): string {
  const lines: string[] = [];
  lines.push(`Course: "${input.courseTitle}" — ${input.courseLessonCount} lesson${
    input.courseLessonCount === 1 ? "" : "s"
  }, ${input.memberCount} member${input.memberCount === 1 ? "" : "s"} tracked.`);
  lines.push(
    `Worst-completion lesson: Lesson ${input.worstPosition} — "${input.worstTitle}" at ${
      Math.round(input.worstCompletionPct * 10) / 10
    }% completion.`,
  );
  if (input.previousPosition !== null && input.previousCompletionPct !== null) {
    lines.push(
      `Previous lesson: Lesson ${input.previousPosition} — "${input.previousTitle}" at ${
        Math.round(input.previousCompletionPct * 10) / 10
      }%.`,
    );
  }
  if (input.nextPosition !== null && input.nextCompletionPct !== null) {
    lines.push(
      `Next lesson: Lesson ${input.nextPosition} — "${input.nextTitle}" at ${
        Math.round(input.nextCompletionPct * 10) / 10
      }%.`,
    );
  }
  lines.push(
    `Write the "What we're seeing" insight for this course. Follow the voice rules in the system prompt strictly.`,
  );
  return lines.join("\n");
}

function extractText(response: Anthropic.Message): string {
  const parts: string[] = [];
  for (const block of response.content) {
    if (block.type === "text") parts.push(block.text);
  }
  return parts.join("").trim();
}

function plural(word: string, n: number): string {
  return n === 1 ? word : `${word}s`;
}

// Convenience export for callers that need to know which shape to
// expect (the cache layer wants this to know whether a row was AI or
// fallback when deciding to upgrade it).
export const INSIGHT_FALLBACK_MODEL = FALLBACK_MODEL_NAME;
export const INSIGHT_ANTHROPIC_MODEL = ANTHROPIC_MODEL;
